title: Zizzla
email: nyfiken@zizzla.com
description: >- # this means to ignore newlines until "baseurl:"
  Precisionsflex - hållbar, värdeskapande och enkel 
url: "https://zizzla.com"
baseurl: ""
logo: "/assets/img/logo.png"

author:
  name: Fredrik Martinsson
  email: fredrik.martinsson@zizzla.com

# Build settings
# plugins:
#   - jekyll-feed
#   - jekyll-sitemap
#   - jekyll-seo-tag
#   - jekyll-redirect-from
#   - jekyll-minifier
#   - jekyll-autoprefixer

zizzla:
  nav_pages:
    - about.markdown
    - services.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
