services:
  jekyll:
    image: jekyll/jekyll:latest 
    container_name: jekyll
    # command: bundle install
    # command: bundle update github-pages 
    command: jekyll serve --port 8000 --livereload 
    ports:
      - 8000:8000
      - 35729:35729
    volumes:
      - .:/srv/jekyll 