services:
  jekyll:
    image: jekyll/jekyll:latest 
    container_name: jekyll
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    # command: bundle update github-pages 
    # command: bundle install
    command: jekyll serve --port 8000 --livereload 
    ports:
      - 8000:8000
      - 35729:35729
    volumes:
      - .:/srv/jekyll 